version: "3.8"

services:

#  app_backend:
#   image:
#   networks:
#     - frontend
#     - backend
#   depends_on:
#     - db
#     - mqtt

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: main_database
      MYSQL_USER: aplication
      MYSQL_PASSWORD: passApp
    networks:
      - backend
    volumes:
      - "./data_db:/var/lib/mysql"
    ports:
      - "33060:3306"

  mqtt:
    image: emqx/emqx
    restart: always
    ports:
      - "18083:18083"   # Puerto para Dashboard
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"


  app_frontend:
    build:
      context: .
      args:
        - "GRAFANA_VERSION=latest"
        - "GF_INSTALL_IMAGE_RENDERER_PLUGIN=true"
        - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
      dockerfile: dockerfile.grafana
    networks:
      - backend
    ports:
      - "3000:3000"


networks:
  backend: